-- Phase 3b: departures and their seat inventory.

create type public.trip_status as enum (
  'SCHEDULED', 'BOARDING', 'DEPARTED', 'ON_TRIP', 'ARRIVED', 'COMPLETED', 'CANCELLED'
);

create type public.trip_seat_status as enum ('AVAILABLE', 'HELD', 'BOOKED', 'BLOCKED');

-- ---------------------------------------------------------------------------
-- Trips
-- ---------------------------------------------------------------------------

create table public.trips (
  id uuid primary key default gen_random_uuid(),
  operator_id uuid not null references public.operators (id) on delete cascade,
  route_id uuid not null references public.routes (id) on delete restrict,
  bus_id uuid not null references public.buses (id) on delete restrict,
  trip_number text not null,
  departure_date date not null,
  departure_time time not null,
  arrival_time time not null,
  -- Money is integer CENTAVOS: ₱450.00 is 45000. Never a float — see
  -- docs/database.md. `integer` caps a single fare at ~₱21.4M, which is ample.
  fare integer not null,
  status public.trip_status not null default 'SCHEDULED',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint trips_fare_positive check (fare > 0),
  constraint trips_number_unique unique (operator_id, trip_number)
);

comment on column public.trips.fare is 'Fare per passenger, in centavos.';

create index trips_departure_date_idx on public.trips (departure_date);
create index trips_route_id_idx on public.trips (route_id);
create index trips_operator_id_idx on public.trips (operator_id);
create index trips_bus_id_idx on public.trips (bus_id);
create index trips_status_idx on public.trips (status);
-- Trip search always filters on route + date together.
create index trips_search_idx on public.trips (route_id, departure_date, status);

create trigger trips_set_updated_at
  before update on public.trips
  for each row execute function public.set_updated_at();

-- ---------------------------------------------------------------------------
-- Trip seat inventory
--
-- One row per sellable seat per departure. This is the table the whole booking
-- system contends on, so note what is NOT here: no client write policy at all.
-- Holds and confirmations happen only inside SECURITY DEFINER functions
-- (`reserve_seats`, Phase 4), which can lock rows and check availability
-- atomically. A client that could UPDATE this table could double-book a seat.
--
-- `booking_id` has no foreign key yet — `bookings` arrives in Phase 4, which
-- adds the constraint.
-- ---------------------------------------------------------------------------

create table public.trip_seats (
  id uuid primary key default gen_random_uuid(),
  trip_id uuid not null references public.trips (id) on delete cascade,
  seat_id uuid not null references public.bus_seats (id) on delete cascade,
  status public.trip_seat_status not null default 'AVAILABLE',
  booking_id uuid,
  held_by uuid references auth.users (id) on delete set null,
  held_until timestamptz,
  confirmed_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint trip_seats_unique unique (trip_id, seat_id),
  -- A hold without an expiry would never be swept up by expire-seat-holds.
  constraint trip_seats_hold_has_expiry check (status <> 'HELD' or held_until is not null)
);

create index trip_seats_trip_id_idx on public.trip_seats (trip_id);
create index trip_seats_status_idx on public.trip_seats (status);
create index trip_seats_booking_id_idx on public.trip_seats (booking_id);
-- The expiry sweep looks for held seats past their deadline.
create index trip_seats_held_until_idx on public.trip_seats (held_until)
  where status = 'HELD';

create trigger trip_seats_set_updated_at
  before update on public.trip_seats
  for each row execute function public.set_updated_at();

-- ---------------------------------------------------------------------------
-- Inventory creation
--
-- Seat inventory is generated by the database when a trip is created, not by
-- whoever created it. A trip that silently has no sellable seats is a failure
-- mode worth designing out entirely.
--
-- DRIVER seats are excluded: they are part of the layout but never sold.
-- ---------------------------------------------------------------------------

create or replace function public.create_trip_seat_inventory()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
begin
  insert into public.trip_seats (trip_id, seat_id, status)
  select new.id, bs.id, 'AVAILABLE'
  from public.bus_seats bs
  where bs.bus_id = new.bus_id
    and bs.seat_type <> 'DRIVER'
    and bs.status = 'ACTIVE';

  return new;
end;
$$;

create trigger trips_create_seat_inventory
  after insert on public.trips
  for each row execute function public.create_trip_seat_inventory();

-- ---------------------------------------------------------------------------
-- Availability
--
-- Trip search needs a seat count per trip. Doing it as a function keeps the
-- definition in one place rather than repeated in every query, and it respects
-- the caller's RLS because it is a plain (INVOKER) function.
-- ---------------------------------------------------------------------------

create or replace function public.trip_available_seats(p_trip_id uuid)
returns integer
language sql
stable
set search_path = ''
as $$
  select count(*)::integer
  from public.trip_seats ts
  where ts.trip_id = p_trip_id
    and (
      ts.status = 'AVAILABLE'
      -- An expired hold is available again; the sweep just has not run yet.
      or (ts.status = 'HELD' and ts.held_until < now())
    );
$$;

-- ---------------------------------------------------------------------------
-- Row Level Security
-- ---------------------------------------------------------------------------

alter table public.trips enable row level security;
alter table public.trip_seats enable row level security;

create policy "Signed-in users read trips"
  on public.trips for select to authenticated using (true);

create policy "Operators write their own trips"
  on public.trips for all to authenticated
  using (operator_id = public.current_operator_id() or public.is_admin())
  with check (operator_id = public.current_operator_id() or public.is_admin());

-- Everyone signed in can SEE the seat map...
create policy "Signed-in users read seat inventory"
  on public.trip_seats for select to authenticated using (true);

-- ...and nobody can write it from a client. Deliberately no insert/update/
-- delete policy: seat state changes only through SECURITY DEFINER functions.
-- Operators blocking a seat for maintenance gets its own function in Phase 7.

revoke insert, update, delete on public.trip_seats from anon, authenticated;
